services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - '.env'
    environment:
      - PGUSER=${POSTGRES_USER}
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    volumes: 
      - './.data/postgres:/var/lib/postgresql/data'
    networks:
      - hexis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 15

networks:
  hexis:
    driver: bridge